version: "3.8"
services:
  ant-hurry-redis:
    container_name: ant-hurry-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: ant-hurry-redis
    ports:
      - "6379:6379"
  ant-hurry-app:
    container_name: ant-hurry-app
    build: .
    depends_on:
      - ant-hurry-redis
    image: ant-hurry-app
    ports:
      - "8086:8080"
    restart: always
  ant-hurry-jenkins:
    container_name: ant-hurry-jenkins
    image: jenkins/jenkins:jdk17
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - "8090:8080"
    user: root
    restart: unless-stopped