spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      database: '${spring.data.mongodb.database}'
      uri: '${spring.data.mongodb.uri}'